(define (last-pair l)
  (if (null? (cdr l))
      (car l)
      (last-pair (cdr l))
      ))
;; (last-pair (list 1 2 3 4 5))
(define (reverse l)
  (define (rev l t)
    (if (null? l)
	t
	(rev (cdr l) (cons (car l) t))
	))
  (rev l '())
  )
(reverse '(1 2 3 4 5))